---
title: "Get time series "
output: html_notebook
---

COVID 19 number of cases over time 

```{r}
pacman::p_load(lubridate,here,  ggrepel,tidyverse)

```


Now use time series and link to file 

```{r}
url_confirmed <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
url_deaths <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"
url_recovered <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"

```

```{r}
n_confirmed <- 
  read_csv(url_confirmed) %>% 
    select(-Lat, -Long) %>% 
    rename(
      lower = `Province/State`,
      higher = `Country/Region`
    ) %>% 
    gather(-lower, -higher, key = "date", value = "n_confirmed") %>% 
    mutate(date = mdy(date))

n_recovered <- 
  read_csv(url_recovered) %>% 
    select(-Lat, -Long) %>% 
    rename(
      lower = `Province/State`,
      higher = `Country/Region`
    ) %>% 
    gather(-lower, -higher, key = "date", value = "n_recovered") %>% 
    mutate(date = mdy(date))

n_deaths <- 
  read_csv(url_deaths) %>% 
    select(-Lat, -Long) %>% 
    rename(
      lower = `Province/State`,
      higher = `Country/Region`
    ) %>% 
    gather(-lower, -higher, key = "date", value = "n_deaths") %>% 
    mutate(date = mdy(date))

tidied_data <- 
  reduce(.x = list(n_confirmed, n_recovered, n_deaths), full_join, by = c("lower", "higher", "date")) %>% 
    gather(key = "type", value = "n", n_confirmed:n_deaths) %>% 
    mutate(type = str_replace(type, pattern = "^n_", ""))


```
Get from series of files 



```{r}
tidied_data %>%
  filter(type == "confirmed") %>%  
  group_by(date) %>% 
  summarise(total_confirmed = sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x = date, y = total_confirmed)) + 
  geom_point()  + 
  scale_y_log10()
  

```

Now after Feb 15


```{r, fig.width = 10, fig.height = 8}
tidied_data %>%
  filter(type == "confirmed") %>%  
  filter(date > lubridate::dmy("15-02-2020")) %>% 
  group_by(date) %>% 
  summarise(total_confirmed = sum(n)) %>% 
  ungroup() %>% 
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  ggplot(aes(x = date, y = total_confirmed)) + 
  geom_point()  + 
  scale_y_log10(  
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
    ) + 
  scale_x_date(date_breaks = "1 day") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  stat_smooth(
    aes(group = month),
    method = "lm", se = FALSE
  ) +
  labs(
    x = "Date", y = "Total cases confirmed (log scale)",
    title = "Total worldwide COVID-19 cases confirmed by date after 15 Feb",
    subtitle = "Log scale. Regression lines broken by month",
    caption = "Source: Johns Hopkins CSSE"
  )

ggsave(here("figures", "covid_19_confirmed_from15feb.png"), height = 20, width = 25, units = "cm", dpi = 300)
  
  

```

Let's look some more about what the data could show 


```{r, fig.height = 8, fig.width = 12}
tidied_data %>% 
  mutate(
    place_category = case_when(
      higher == "China" & lower == "Hubei" ~ "Hubei, China",
      higher == "China" & lower != "Hubei" ~ "Rest of China",
      TRUE                                 ~ "Rest of World"
    )
  ) %>% 
  group_by(date, place_category, type) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x = date, y =  n, group = place_category, linetype = place_category)) + 
  facet_wrap(~type) + 
  geom_line() +
  scale_y_log10(    
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
) + labs(
  x = "Date", y = "Number of cases (Log scale)",
  title = "Confirmed cases, deaths, and recovered",
  subtitle = "Hubei, Rest of China, and Rest of World",
  caption = "Source: Johns Hopkins CSSE"
) + 
  scale_linetype_discrete("Location")

ggsave(here("figures", "confirmed_deaths_recovered.png"), height = 15, width = 20, units = "cm", dpi = 300)

```

```{r}
# Countries with at least 100 confirmed cases on 8/3/20

big_case_countries <- 
  tidied_data %>% 
    filter(type == "confirmed") %>% 
    group_by(date, higher) %>% 
    summarise(n = sum(n)) %>% 
    ungroup()  %>% 
    filter(date == max(date)) %>% 
    arrange(desc(n)) %>% 
    filter(n > 100) %>% 
    pull(higher)

tidied_data %>% 
  mutate(country = case_when(
    higher %in% big_case_countries ~ higher,
    TRUE                           ~ "Other"
    )
  ) %>% 
  filter(type == "confirmed") %>% 
  group_by(date, country) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x = date, y = n)) + 
  geom_line() +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  facet_wrap(~country)

ggsave(here("figures", "confirmed_cases_atleast100.png"), height = 25, width = 25, units = "cm", dpi = 300)


```

What's the gradient of increase for these countries since 1 March? 

```{r}
get_gradient_fit <- function(dta){
  num_cases <- dta %>% 
    filter(date == max(date)) %>% 
    pull(n) 
  
  model <- lm(log(n) ~ date, data = dta)
  slope <- coefficients(model)[["date"]]
  rsq <- summary(model)$r.squared
  
  return(tibble(
    num_cases, slope = slope, r_squared = rsq
  ))
}


tidied_data %>% 
  filter(date >= lubridate::dmy("29-02-20")) %>%
  filter(higher %in% big_case_countries) %>% 
  filter(type == "confirmed") %>% 
  filter(higher != "Others") %>% 
  group_by(date, higher) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  group_by(higher) %>% nest() %>% 
  mutate(results = map(data, get_gradient_fit)) %>% 
  select(higher, results) %>% 
  unnest(results) %>% 
  arrange(desc(slope)) %>% 
  ggplot(aes(x = r_squared, y = slope, alpha = log(num_cases))) + 
  geom_point() + 
  theme(legend.position = "none") + 
  scale_x_continuous(limits = c(0.8, 1.0)) +
  geom_text_repel(aes(label = higher), alpha = 1) + 
  labs(
    x = "R-squared (Higher= more log-linear)",
    y = "Slope (Higher= faster % growth rates)",
    title = "Steepness of case growth rate against model fit",
    subtitle = "Countries with at least 100 cases on 8 March 2020. Darker dots = More cases",
    caption = "Source: Johns Hopkins CSSE"
  )

ggsave(here("figures", "rate_of_increase_against_model_fit.png"), height = 15, width = 15, units = "cm", dpi = 300)


```

Look at rate of increase once 100 cases identified 


```{r}
tidied_data %>% 
  filter(type == "confirmed") %>% 
  filter(higher != "Cruise Ship") %>% 
  group_by(higher, date) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  group_by(higher) %>% 
  arrange(date) %>% 
  filter(n >= 100) %>%
  mutate(first_date = date[1]) %>% 
  mutate(days_since_first = date - first_date) %>% 
  mutate(max_days_since_first = max(days_since_first)) %>% 
  ungroup() %>% 
  mutate(country = fct_reorder(higher, desc(max_days_since_first))) %>%
  filter(country != "Others") %>% 
  ggplot(aes(x = days_since_first, y = n)) +
  geom_line() + 
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) + 
  facet_wrap(~country) +
  labs(
    title = "Confirmed cases after first 100 cases",
    subtitle = "Arranged by number of days since 100 or more cases",
    x = "Days after 100 confirmed cases",
    y = "Confirmed cases (log scale)", 
    caption = "Source: Johns Hopkins CSSE"
  )

ggsave("figures/days_since_100.png", height = 20, width = 20, units = "cm", dpi = 300)

```


Alternative presentation (from [here](https://github.com/gorkang/2020-corona/blob/master/2020-corona-plot.R))

```{r}
days_since_data <- 
  tidied_data %>% 
    filter(type == "confirmed") %>% 
    filter(higher != "Cruise Ship") %>% 
    group_by(higher, date) %>% 
    summarise(n = sum(n)) %>% 
    ungroup() %>% 
    group_by(higher) %>% 
    arrange(date) %>% 
    filter(n >= 100) %>%
    mutate(first_date = date[1]) %>% 
    mutate(days_since_first = date - first_date) %>% 
    mutate(max_days_since_first = max(days_since_first)) %>% 
    ungroup() %>% 
    mutate(country = fct_reorder(higher, desc(max_days_since_first))) %>%
    mutate(country_label = glue::glue("{country}, {max_days_since_first} days")) %>% 
    filter(country != "Others") 

days_since_data %>% 
  ggplot(aes(x = days_since_first, y = n, group = country, colour = country_label)) +
  geom_line() + 
  ggrepel::geom_label_repel(aes(label = country_label), show.legend = FALSE, segment.color = "grey", nudge_x = 10,  
                            data = days_since_data %>% 
                              group_by(country) %>% 
                              filter(days_since_first == max(days_since_first)) %>% 
                              filter(days_since_first >= 5)
                            ) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) + 
  labs(
    title = "Confirmed cases after first 100 cases",
    subtitle = "Arranged by number of days since 100 or more cases. Countries with 5 or more days labelled",
    x = "Days after 100 confirmed cases",
    y = "Confirmed cases (log scale)", 
    caption = "Source: Johns Hopkins CSSE"
  ) +
  theme(
    legend.position = "none"
  )

ggsave(here("figures", "days_since_100_oneplot.png"), height = 15, width = 25, units = "cm", dpi = 300)


```

Let's try to model this (China and not China to start with)

```{r}
tidied_data %>% 
  mutate(
    place_category = case_when(
      higher == "China" & lower == "Hubei" ~ "Hubei, China",
      higher == "China" & lower != "Hubei" ~ "Rest of China",
      TRUE                                 ~ "Rest of World"
    )
  ) %>% 
  group_by(date, place_category, type) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  filter(n >= 100) %>% 
  ggplot(aes(x = date, y = n, group = type, linetype = type)) + 
  geom_line() + 
  facet_wrap(~place_category) + 
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  labs(
    y = "Number of cases", 
    x = "Date"
  )

```


