---
title: "Mapping example"
output: html_notebook
---


# Aim 

In this document I'm going to go through the tutorial available here:

* [Part 1](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html)
* [Part 2](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html)
* [Part 3](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-3.html)


# Part 1

Prereqs 

```{r}
pacman::p_load(
  cowplot, 
  googleway,
  tidyverse, 
  ggrepel,
  ggspatial,
  libwgeom,
  sf,
  rnaturalearth,
  rnaturalearthdata
)

```

Set theme

```{r}
theme_set(theme_bw())

```


country from rnaturalearth

```{r}
# ?ne_countries 
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

Visualise 

```{r}
world %>% 
  ggplot() + 
  geom_sf()

```

Look at `world`

```{r}
glimpse(world)

```

Good. This should make it relatively straightforward to join 


```{r}
ggplot(data = world) +
    geom_sf() +
    xlab("Longitude") + ylab("Latitude") +
    ggtitle("World map", subtitle = paste0("(", length(unique(world$name)), " countries)"))

```


```{r}
ggplot(data = world) +
    geom_sf(aes(fill = pop_est)) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")


```


Labels 

```{r}
world_points<- st_centroid(world)
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))

ggplot(data = world) +
  geom_sf() +
  geom_text(data= world_points,aes(x=X, y=Y, label=name),
      color = "darkblue", fontface = "bold", check_overlap = FALSE) +
  annotate(geom = "text", x = -90, y = 26, label = "Gulf of Mexico", 
      fontface = "italic", color = "grey22", size = 6) +
  coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE)

```



# Part 2

```{r}
(sites <- data.frame(longitude = c(-80.144005, -80.109), latitude = c(26.479005, 
    26.83)))

ggplot(data = world) +
    geom_sf() +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)

```


Converting sites to sf object 


```{r}
(sites <- st_as_sf(sites, coords = c("longitude", "latitude"), 
    crs = 4326, agr = "constant"))


ggplot(data = world) +
    geom_sf() +
    geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)

```

I think the above is actually about all I need. Let's try this with the data we have 



